### ISSUE TITLE
MavenBinaryInstaller Setting loose POSIX file permissions is security-sensitive java:S2612

### ISSUE THREAD

**Issue by kevinhagel** [webforj/webforj#532]
Sonarcloud reports two instances of the security hotspot as quoted below.  These are the setting of posix file permissions for the mvn.cmd and mvn files when installing maven.  We are in a potential multi-user environment.  There is also the potential UnsupportedOperationException thrown when attempting to set the posix permissions in a Windows environment

- Remove write permissions for Group and Others.  Leave read and execute permissions for Group and Others.
- Add commons-lang3 to project to obtain SystemUtils library, this is available in the parent structure.
- Test for Posix supported file systems, do not try to run on windows.

> Setting loose POSIX file permissions is security-sensitive[java:S2612](https://sonarcloud.io/organizations/dwcjava/rules?open=java%3AS2612&rule_key=java%3AS2612)
> 
> In Unix file system permissions, the "others" category refers to all users except the owner of the file system resource and the members of the group assigned to this resource.
> Granting permissions to this category can lead to unintended access to files or directories that could allow attackers to obtain sensitive information, disrupt services or elevate privileges.
> Ask Yourself Whether
> The application is designed to be run on a multi-user environment.
> Corresponding files and directories may contain confidential information.
> There is a risk if you answered yes to any of those questions.

**Comment by StephanWald** [comment]
Due to the nature of BBj, the permission for "others" is in many cases needed. BBjServices may oftentimes run as "root", while the servlets (that are executing the BBj process that triggers the mvn install) will ultimately run as "nobody" or some other unprivileged user. Limiting the execution to r-x------ would render the statement pointless.

**Comment by kevinhagel** [comment]
what does "render the statement pointless" mean?
Should we allow this security hotspot to be reviewed as Won't Fix?  It is only of medium concern.
I can just cancel this issue ¯\_(ツ)_/¯

**Comment by StephanWald** [comment]
Leave it in for now. The additional explanation is useful for later
reconsideration. WONTFIX is not good, I fully agree with you. We need to
review this at a later point, after the webforJ ecosystem with the new
installer is ready.

ppa. Stephan Wald

Director of Sales and Technical Service Europe
BASIS Europe Distribution GmbH

*Story: Bitburger setzt bei der Koordination der Logistik auf BASIS und
brevis.one...
<https://brevis.one/de/brevis.one_Bitburger.html?utm_source=Email&utm_medium=Signatur&utm_campaign=sw>*

Nell-Breuning-Allee 6 | 66115 Saarbruecken, Germany
Phone: +49 681 9 68 14-23 |  US +1 (505) 585-1358 | Fax +49 681 9 68 14-33

Managing Director: Nico Spence | Company Register HRB Saarbruecken 16820
www.basis-europe.eu

**Comment by kevinhagel** [comment]
I've modified the list of things to do in the bug report.
In my branch I have tested for IS_OS_MAC or IS_OS_LINUX, avoiding the permssions issue on windows.
Owner is rwx
Group is r-x
Others is r-x 
now:  rwxr-xr-x

I have not seen the maven binary installer in action in real environments so i need to access your experience in this.
