### ISSUE TITLE
NumericBox should support BigDecimal by default

### ISSUE THREAD

**Issue by StephanWald** [webforj/webforj#61]

**Comment by Oskan1** [comment]
I tried to pass the code to checkStyleForJava extension. Link: https://github.com/DwcJava/engine/tree/issue%2361

**Comment by hyyan** [comment]
According to the docs , BBjInputN supports only floats. 
https://documentation.basis.cloud/BASISHelp/WebHelp/bbjobjects/Window/bbjinputn/bbjinputn_setvalue.htm

**Comment by hyyan** [comment]
Update: The implementation will support `Double`, the client component cannot handle `BigDecimal` at the moment
