### ISSUE TITLE
Controls do not get focused from calling focus() when they've been just enabled by calling setEnabled.

### ISSUE THREAD

**Issue by TimonGeisbauer** [webforj/webforj#632]
When trying to focus a control after it has been enabled it does not focus the control. 
Using a Timer as a workaround works. I used 100milliseconds.
After the control is enabled the workaround is not needed. The Focus is applied directly.

webforj Version 24.02 
Docker image RC (27.06.24)

**Comment by hyyan** [comment]
A fix is available in BBj 24.10RC
