### ISSUE TITLE
[BUG] WebforJRuntimeException: Failed to create component Div

### ISSUE THREAD

**Issue by user-4321431243** [webforj/webforj#635]
**Describe the bug**
When loading the app the first time after a compile everything works also the swap and update. but if you refresh the browser and do the swap again it errors.
link with code for recreation https://github.com/user-4321431243/DivCreationCrash
**To Reproduce**
1. Launch App
2. Click "Music"
3. Reload App in Brower with F5 or Button
4. Click "Music" again.

**Expected behavior**
swaping the content like it does the first time

**Screenshots**
![image](https://github.com/webforj/webforj/assets/142789373/7653cec6-a9a9-48ba-aad9-a282cde4ee28)

**Software Versions**
 - Java Version: 17.0.8
 - DWCJ version: 24.02
 - BBj Version: 24.02

**Desktop:**
 - OS: Windows 11
 - Browser Brave
 - Version: Brave: 1.67.123 Chromium: 126.0.6478.126

**Additional context**
# Scenario
You have an applayout and want to have the Content switch between "child windows". What I do is I have a Div in the content which I replace with a Div
returned by the testTab.getSubframe.
But because when I swap the content div with the return from the getSubframe it doesn't update the client. so I remove the content div, swap it and add it back. The reason because .getSubframe returns a copy of the actual Subframe is because applayout.remove seems to call destroy on the Component making the readd break.

**Comment by hyyan** [comment]
A servlet is created only once during a web application's startup and is shared among all requests, which means static variables are shared as well. Static variables do not belong to any single instance; they are accessible by all instances of the class. To prevent sharing of static members, avoid using statics. In your case one possible solution is to use `ObjectTable` to store the instance. `ObjectTable` provides access to a map of key-value pairs that is accessible throughout the program. Ensure the key is unique to your class.


```java
  public static testTab getInstance() {
    // if (instance == null) {
    // instance = new testTab();
    // }
    // return instance;

    String key = "testTab__instance__uuid";
    if (ObjectTable.contains(key)) {
      return (testTab) ObjectTable.get(key);
    } else {
      testTab instance = new testTab();
      ObjectTable.put(key, instance);
      return instance;
    }
  }
```
