### ISSUE TITLE
[BUG] Table looses its height when Parent Composite<Div> is toggled from visible to invisible and Back

### ISSUE THREAD

**Issue by ckochaneck** [webforj/webforj#656]
**Describe the bug**
[BUG] Table looses its height when Parent `Composite<Div>` is toggled from visible to invisible and Back.

**To Reproduce**
1. Create a Class that extends `Composite<Div>` and implements `HasVisibilty<Div>` <br> Add a Table to the bound component.
2. Set the instance of that class invisible using `setVisible(false)`
3. Set the instance of that class visible using `setVisible(true)`
4. The table now still has its width, but the height is 0.

**Expected behavior**
The table should not loose its height when the parent's visibility State toggles

**Software Versions (please complete the following information)**
- Container: https://hub.docker.com/r/webforj/sandbox
- Container Version: webforj/24.02

**Comment by hyyan** [comment]
@ckochaneck I am unable to reproduce the issue.  Please provide a sample code that demonstrates the problem?

**Comment by hyyan** [comment]
@ckochaneck try to modify the following:

```java
package addondemos.tabledemos;

import com.webforj.App;
import com.webforj.Environment;
import com.webforj.component.Composite;
import com.webforj.component.html.elements.Div;
import com.webforj.component.table.Table;
import com.webforj.component.window.Frame;
import com.webforj.concern.HasVisibility;
import com.webforj.exceptions.WebforjException;

public class TableBasic extends App {

  @Override
  public void run() throws WebforjException {
    Com c = new Com();
    c.setVisible(false);
    Frame mainFrame = new Frame();
    mainFrame.add(c);

    Environment.getCurrent().sleep(5);
    c.setVisible(true);
  }

  public class Com extends Composite<Div> implements HasVisibility<Com> {

    public Com() {
      Table<MusicRecord> table = new Table<>();
      table.setStyle("width", "100vw");
      table.setStyle("height", "100vh");

      table.addColumn("Number", MusicRecord::getNumber);
      table.addColumn("Title", MusicRecord::getTitle);
      table.addColumn("Artist", MusicRecord::getArtist);
      table.addColumn("Genre", MusicRecord::getMusicType);
      table.addColumn("Cost", MusicRecord::getCost);

      table.setRepository(Service.getMusicRecords());

      getBoundComponent().add(table);
    }
  }
}

```

**Comment by ckochaneck** [comment]
The problem indeed seems to be within the use case here. The structure being is contains nested Divs within in the Composite. What happens is that the setVisible method changes the "display" property from "block" to "none" and therefore overwrites my custom "display: grid" property, which leads to the Table not being shown.

A workaround for that is to add a Div at the Composite Level and store all your content within there, so any display styles do not interfere with the setVisible.

A proper solution could be to not display properties to change visibility states, but rather use the visibility or to remember the previously set display property and set it back to that.

**Comment by hyyan** [comment]
#669
