### ISSUE TITLE
[BUG] Inconsistent behavior when retrieving non-existent and null values from web storage

### ISSUE THREAD

**Issue by MatthewHawkins** [webforj/webforj#657]
**Describe the bug**
Using web storage, when you retrieve the value of a key that doesn’t exist, it returns an empty string. When you retrieve the value of a key which has existed and is set to null, it returns a string “null”. Is this expected behavior? If so, disregard.

```java
 @Override
  public void run() throws WebforjException {
    LocalStorage localStorage = LocalStorage.getCurrent();
    App.consoleLog(localStorage.get("theme"));
    localStorage.add("theme", "dark");
    App.consoleLog(localStorage.get("theme"));
    localStorage.remove("theme");
    App.consoleLog(localStorage.get("theme"));
  }
```
Chrome browser
Windows OS
24.02 webforJ

**Comment by hyyan** [comment]
Fix in BBj 24.11
