### ISSUE TITLE
BrowserConsole font-size: larger is smaller than font-size: large.

### ISSUE THREAD

**Issue by bbrennanbasis** [webforj/webforj#674]
**Description**
While using the BrowserConsole class, I discovered that the size().larger() method prints out smaller than the size().large() method.

**To Reproduce**
1. Import the <code>App</code> class
2. Run the following code snippet:
<code>console().size.larger.log("text");</code>
<code>console().size.large.log("text");</code>
3. Compare sizes in the browser console output

**Software Versions**
 - Java Version: jdk 21.02+13
 - webforJ/sandbox Tag: 24.10
 - Google Chrome Version 127.0.6533.73 (Official Build) (64-bit)

**Comment by hyyan** [comment]
Thanks Ben. fix in 24.11-SNAPSHOT
