### ISSUE TITLE
[Feature] Enable NumberField to handle int Values

### ISSUE THREAD

**Issue by ckochaneck** [webforj/webforj#690]
**Describe the solution you'd like**
The NumberField should be able to not only take double Values as Parameter, but also int Values. It should then also display them in an  int format and not as a double.

This enables Developers to also directly pass int Values withouth casting from String/int to double and enables them to easily display int Values and ensure safety without providing an extra Validation to check if the Value contains String elements.

**Comment by hyyan** [comment]
After testing, this has been implemented as planned. The component should only work with doubles. The following #835 improves the component’s logic to detect when a number can be displayed as an integer and display it correctly.

```java
NumberField numberField = new NumberField("Enter a number");
numberField.setValue(100.0);
```


<img width="357" alt="Screenshot 2024-12-05 at 7 01 40 AM" src="https://github.com/user-attachments/assets/ba897162-318e-4d23-969f-2982c995ccf6">
