### ISSUE TITLE
[Feature] Implement a setItems(Collection<T> items) method for ComboxBox

### ISSUE THREAD

**Issue by ckochaneck** [webforj/webforj#699]
**Describe the solution you'd like**
A method should exist that lets Developers use a setItems method, so they don't have to manually check for duplicates and don't have to iterate through a set of Items their selves.

Desired Features:
- Automatic Deduplication
- Passing a list directly without the need to call `add` for every Item individually

**Comment by hyyan** [comment]
@ckochaneck Have you tried `insert` method. It is meant for bulk inserting:

https://javadoc.io/doc/com.webforj/webforj-foundation/latest/com/webforj/component/list/DwcList.html#insert(int,com.webforj.component.list.ListItem)

**Comment by hyyan** [comment]
@ckochaneck also check: https://documentation.webforj.com/docs/components/list-components/lists#managing-listitem-objects-with-the-api

**Comment by ckochaneck** [comment]
The insert method still requires to build a List of ListItems first, which defeats the purpose.

**Comment by hyyan** [comment]
@ckochaneck what are you expecting to pass to the method ? What "T" refers to in Collection ?
