### ISSUE TITLE
[BUG] Img component shows wrong image

### ISSUE THREAD

**Issue by lholzapfelbasis** [webforj/webforj#713]
**Describe the bug**
If you use the context link for an image source and your image is in the "images" folder, you get an Placeholder image.
If i load the image directly from the Resource folder, then it gets displayed properly

**To Reproduce**
1. make an Img()
2. set the source to "context://images/logo.png
3. put the logo.png image in the resources/images folder

**Expected behavior**
Display the proper image

**Screenshots**
This is the Image that gets loaded:
![grafik](https://github.com/user-attachments/assets/3b1e8e0c-eea2-4035-ab56-0cfe66395b46)

**Software Versions (please complete the following information)**
 - Webforj 24.10

**Comment by hyyan** [comment]
@lholzapfelbasis, what do you mean by "you get a placeholder image"? If something is being served, then the context URL is resolving as expected. Have you tried testing it in an incognito window?
