### ISSUE TITLE
[DOCS] Replace DWCJ with webforJ

### ISSUE THREAD

**Issue by bbrennanbasis** [webforj/webforj#733]
[CONTRIBUTING.md](https://github.com/webforj/webforj/blob/main/CONTRIBUTING.md) and [README.md](https://github.com/webforj/webforj/blob/main/README.md) refer to DWCJ instead of webforJ.

- [CONTRIBUTING.md](https://github.com/webforj/webforj/blob/main/CONTRIBUTING.md)
DWCJ is mentioned multiple times, more than 21 instances.

- [README.md](https://github.com/webforj/webforj/blob/main/README.md)
DWCJ is mentioned in the **Examples** and **Documentation** sections.

**Comment by bbrennanbasis** [comment]
@hyyan This issue is not complete, [CONTRIBUTING.md](https://github.com/webforj/webforj/blob/main/CONTRIBUTING.md) still has multiple cases of DWCJ.

**Comment by hyyan** [comment]
@bbrennanbasis https://github.com/webforj/webforj/issues/810
