### ISSUE TITLE
[BUG] MaskedNumberInput::setReadOnly does not work

### ISSUE THREAD

**Issue by ckochaneck** [webforj/webforj#738]
**Describe the bug**
When using the MaskedNumberInput method setReadOnly(boolean), the method does not seem to have any effect.

**To Reproduce**
1. Initialize a MaskedNumberInput 
2. Use the method setReadOnly(true)
3. Set a mask, e.g. "##########"
4. The Input Value is still editable, despite being set ReadOnly

**Expected behavior**
The Input should not be editable when set Read Only.

**Comment by hyyan** [comment]
duplicate of #697. Fixed in `24.11`
