### ISSUE TITLE
[BUG] TablerIcons with a defined variate do not load

### ISSUE THREAD

**Issue by bbrennanbasis** [webforj/webforj#748]
### Issue
SVGs fail to load when creating an Icon with the `TablerIcon` class that has a defined variate.

### Replication
1. Pick an icon from [Tabler](https://tabler.io/icons) that has a filled and outline variant, like [alert-octagon](https://tabler.io/icons/icon/alert-octagon)

2. Add the icon in your program with a defined variate
`Icon octagonFilled = TablerIcon.create("alert-octagon", TablerIcon.Variate.FILLED);`
   or
`Icon octagonOutline = TablerIcon.create("alert-octagon", TablerIcon.Variate.OUTLINE);`

3. Add the same icon without a variate as a control group
`Icon octagon = TablerIcon.create("alert-octagon");`

4. Run and observe

### Warning messages from console
- Failed to load the SVG icon: https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/filled-alert-octagon.svg
- Failed to load the SVG icon: https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/outline-alert-octagon.svg

**Comment by hyyan** [comment]
Fixed in 24.12
