### ISSUE TITLE
[BUG] FlexLayout is not affected by setVisible(false)

### ISSUE THREAD

**Issue by ckochaneck** [webforj/webforj#757]
#### Description:
When calling `setVisible(false)` on a component inside a `FlexLayout`, the component remains visible. The expected behavior is that setting `setVisible(false)` should hide the component from the layout, but it continues to take up space and render as if it were still visible.

#### Steps to Reproduce:
1. Create a simple `FlexLayout` with a few child components.
2. Call `setVisible(false)` on one of the child components.
3. Observe that the component remains visible in the layout.

#### Expected Behavior:
- The component should be hidden from the layout and not take up space when `setVisible(false)` is called.

#### Actual Behavior:
- The component is still rendered and takes up space in the layout, even after calling `setVisible(false)`.

#### Additional Information:
- This issue may be related to how `FlexLayout` handles visibility flags or its child component layout management.

#### Workaround:
Currently, the only workaround is to change the CSS styling for the layout manually.

#### Screenshots/Code Snippets:
```java
FlexLayout layout = new FlexLayout();
component.add(layout);

// Setting button to invisible
layout.setVisible(false);

**Comment by hyyan** [comment]
@ckochaneck I cannot reproduce this, which version do you use ?
