### ISSUE TITLE
[BUG] Components in the content slot of a `Toolbar` only align in the center if there is a component in the title slot

### ISSUE THREAD

**Issue by bbrennanbasis** [webforj/webforj#790]
## Describe the bug
If no components are added to the `title` slot of a `Toolbar`, the components in the `content` slot do not align in the center.

## To Reproduce
1. Add the following snippet:
```java
Icon dashboard = TablerIcon.create("dashboard");
Icon orders = TablerIcon.create("shopping-cart");
Icon customers = TablerIcon.create("users");

Toolbar toolbar = new Toolbar();
toolbar.addToContent(orders, customers);
toolbar.addToTitle(dashboard);
```
3. Run and observe behavior
4. Comment out (or remove) the last line that adds a title component:
```java
Icon dashboard = TablerIcon.create("dashboard");
Icon orders = TablerIcon.create("shopping-cart");
Icon customers = TablerIcon.create("users");

Toolbar toolbar = new Toolbar();
toolbar.addToContent(orders, customers);
// toolbar.addToTitle(dashboard);
```
5. Run and observe behavior

## Expected behavior
I expected the content to be in the center of the toolbar, regardless if there was a component in the title slot.

## Screenshots
**With a title component**
![with-title-slot](https://github.com/user-attachments/assets/e8659e6a-fc2b-4365-a7c0-9e851966eb17)
**Without a title component**
![content-slot-only](https://github.com/user-attachments/assets/300a6926-107e-4714-9130-3c590acfd678)

## Version
This issue was discovered in 24.12.

**Comment by hyyan** [comment]
The section is called "content," not "center." It's the title that's pushing the content to the center.
