### ISSUE TITLE
CamelCase AutoFocus methods for `Dialog`

### ISSUE THREAD

**Issue by bbrennanbasis** [webforj/webforj#833]
CamelCase the following methods:

https://github.com/webforj/webforj/blob/3bc6238881dc126ac360df4fe5fea5550da24d8f/webforj-components/webforj-dialog/src/main/java/com/webforj/component/dialog/Dialog.java#L174

https://github.com/webforj/webforj/blob/3bc6238881dc126ac360df4fe5fea5550da24d8f/webforj-components/webforj-dialog/src/main/java/com/webforj/component/dialog/Dialog.java#L184

There are similar methods for `DwcField` in CamelCase:

https://github.com/webforj/webforj/blob/3bc6238881dc126ac360df4fe5fea5550da24d8f/webforj-foundation/src/main/java/com/webforj/component/field/DwcField.java#L252

https://github.com/webforj/webforj/blob/3bc6238881dc126ac360df4fe5fea5550da24d8f/webforj-foundation/src/main/java/com/webforj/component/field/DwcField.java#L264

**Comment by hyyan** [comment]
This is the correct capitalization for these methods.

**Comment by hyyan** [comment]
Ah. I see. reopen
